name: pekky
description: "An alternative mobile app for the polish transport service Peka."
publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  http: ^1.3.0
  dynamic_color: ^1.7.0
  uuid: ^4.5.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true